### ISSUE TITLE
Change the How to Buy and Phone number CTA

### ISSUE THREAD

**Issue by RassanGrant** [Norstone/norstone.github.io#220]
Hi @vleong2332 - 

You may have noticed that the phone number and How to Buy button at the top right of our website are, together, a static png. image. I did this a long time ago because I did not know how to turn that into a button and a real, clickable html phone number. Would you be able to convert what's there into a button (with hover state) and a clickable html phone number? I would like them to look roughly the same as they are now in terms of scale and aesthetic. 

For the button, however, I am liking the Shopify button styling we have - Are you able to replicate that for the How to Buy button? 

![2017-12-14 02 46 55 pm](https://user-images.githubusercontent.com/18408413/34011322-a93a3e72-e0dd-11e7-99cd-8f0fafc41fbc.png)

**Comment by vleong2332** [comment]
@RassanGrant On the home page, I see that the "How To Buy" button is an image. I can definitely change that to a real HTML button that looks like the Shopify button. I'm estimating 20-40 minutes of work for that.

As for the telephone number, it's already a clickable link.

**Comment by RassanGrant** [comment]
Perfect, let's do it. Just try to keep the scale of the button the same as the .gif (small) even though it will have the same styling as the Shopify button.

**Comment by vleong2332** [comment]
@RassanGrant what should happen when you click "How to buy" button?

**Comment by vleong2332** [comment]
@RassanGrant the current progress is in `shopify` branch. I don't see any action for the button so it's not doing anything right now. Let me know what you want the button to do and I can complete this.

**Comment by RassanGrant** [comment]
This looks great, thanks Vicky

**Comment by RassanGrant** [comment]
Do you have a way of pushing only this change to live? If so I'd be willing to see it go live.

**Comment by vleong2332** [comment]
Yes. I can do it tonight.

**Comment by vleong2332** [comment]
Done.
