### ISSUE TITLE
Dynamic Footer

### ISSUE THREAD

**Issue by RassanGrant** [Norstone/norstone.github.io#221]
HI @vleong2332 - 

I have also long been interested in updating our footer as well. I recently updated a very basic html version of what you see in the footer now, but I would like something a little more dynamic - I put together a visual idea which I've attached here. Could you build it?

![site-footer-v2](https://user-images.githubusercontent.com/18408413/34012308-45ab0982-e0e1-11e7-874a-ea9350e85aec.jpg)

**Comment by vleong2332** [comment]
I can. Could you tell me more about that prototype? Things that will help me are:

1. How do you want the footer to look like for a small (mobile) screen?
2. How do you want the footer to look like for a wide (desktop) screen?
3. How do you want the elements (button, links, row) to look like on hover?
4. Do you want to only show two galleries?
5. Do you want the list of products to be "synced" with what you have for products?
6. Do you want the list of galleries to be "synced" with what you have for galleries?

Number 5 and 6 could be more complex if you want them to be "synced".

**Comment by RassanGrant** [comment]
Hey @vleong2332, Answers as follows:

1. We can make it a longer mobile footer, like you see on the .com.au site: https://www.norstone.com.au/
2. The image I pasted earlier is how we'd like it for desktop. 
3. On hover, the button can act the same as the button currently on our Products pages. For links on hover, you might try something similar to this page: https://generalassemb.ly/. If it's too complex then just an elevated color state (brighter white) is sufficient.
4. I would like to show a minimum of 4 galleries, preferably 6 or 8. 
5. Products do not need to be synced, just linked out to those pages.
6. Likewise, does not need to be synced, just linked to galleries of our choosing. 

No worries on the sync part for now. Thanks Vicky!

**Comment by vleong2332** [comment]
Hi, @RassanGrant, thanks for the detail. The work will involve gutting the markup, putting up new layout, contents, and styling, making the layout responsive, and polishing the links and buttons with hover effects. I'm estimating 1 hour to 1.5 hour for this.

**Comment by RassanGrant** [comment]
Hey @vleong2332 - Did you get around to adjusting the paragraph text and those other points from Slack?

Couple quick things: 1. can we change the border top (the lines between the links) to ##ababab 2. I am pushing up some new text for the <p> content on the left hand side. Can you adjust the spacing between the lines of text to be typical reading line height? I am also interested in having the paragraph font to be Open Sans 3. Let’s make the phone number clickable 4. Let’s make the Copyright “2013” to be a dynamic date which is automatically updated (like it is now {{ site.time | date: ‘%Y’ }}) 5. I’m fairly certain we have a number of scripts being published in the footer, let’s make sure those get monitored and added back in so we don’t lose any tracking capabilities on the site


[11:29] 
Oh one other thing on this Vicky - Can we change the top two blocks to “Shop our Products” (first block) second “Browse our Galleries” (Second block) and then “Company (third block)


vicky.leong [11:36 AM] 
1. yes, no problem.
2. I see your changes.
  a. The line height remains the same in the footer as it is in the body (1.6). Do you want me to reduce them so the lines are closer together?
  b. Open Sans just for that paragraph (`site-description`) or for everything in the footer?
3. Ok.
4. Sure.
5. I've moved the scripts to their own file `_scripts.html` for this reason. It's being included after the footer element.
6. Yes. (edited)

**Comment by vleong2332** [comment]
@RassanGrant Yes I did. It should be up on `shopify` branch.

**Comment by RassanGrant** [comment]
Hi @vleong2332 - Home stretch on this one. Can you please do the following for me?

1. Shift the links on the far right/bottom down so they line up with the links under Resources (they belong to that section)
2. Make the font color for just the links under products and galleries #7cdfec

That should wrap this up - Thanks!

**Comment by vleong2332** [comment]
Hi, @RassanGrant. Would you clarify what you meant by Resources for number 1? I can change the font color for number 2.

**Comment by vleong2332** [comment]
I see that you've changed "Company" to "Resources". So you want the "What our customers say", "Contact us", and "Register a project" to shift down a little bit.

**Comment by vleong2332** [comment]
Pushed changes. I did a quick and dirty fix for number 2. The way the markup is setup, on the smaller screen, you'll see the gap between the first set three links and the second set three links. I have a feeling that you want the lists to be laid out differently, but I don't want to assume because making layout changes is not as trivial.
