### ISSUE TITLE
Re-adjust the Quickview Tab for Lynia Tiles

### ISSUE THREAD

**Issue by RassanGrant** [Norstone/norstone.github.io#226]
Hey @vleong2332 - I believe that when you updated the mobile layout for the Quickview Tabs last month, you may have inadvertently adjusted the default desktop layout of the lynia - Could you look into changing it back? The reason I am thinking it should be changed back is that it is messing with the spacing between the Lynia and Aksent 3D blocks on the product page: https://www.norstoneusa.com/products/

This is what it used to look like:

<img width="981" alt="2018-01-22 05 40 04 pm" src="https://user-images.githubusercontent.com/18408413/35248282-94b34be2-ff9b-11e7-9ad9-a75ad59feb87.png">

Here is what it looks like currently:

<img width="791" alt="2018-01-22 05 42 40 pm" src="https://user-images.githubusercontent.com/18408413/35248372-db41fc66-ff9b-11e7-8b95-d81a2687376d.png">

![2018-01-22-05 42 51-pm](https://user-images.githubusercontent.com/18408413/35248412-f5d2fe4a-ff9b-11e7-8a0c-8fdf4306ea67.jpg)

**Comment by vleong2332** [comment]
Hmm. I'll take a look and fix it. If it was my fault, there won't be any charge.

**Comment by vleong2332** [comment]
It was my mistake. I've written a fix which is up on branch `fix-lynia-tiles-quiickview`. Would you verify that it works as you intended?

**Comment by RassanGrant** [comment]
Hey Vicky - Thanks for this, I made a few additional edits and will merge!
