### ISSUE TITLE
Gallery Subnav Arrow Correction

### ISSUE THREAD

**Issue by RassanGrant** [Norstone/norstone.github.io#231]
Hi @vleong2332 - 

https://www.norstoneusa.com/gallery/rock-panels/ochre/ - See the active state in the gallery menu navigation? You will see it has a small **grey arrow** that points up at the gallery section you are currently on - I'm not sure why, but at some point it looks like it became misaligned: 
<img width="206" alt="2018-01-23 03 08 36 pm" src="https://user-images.githubusercontent.com/18408413/35298182-526603b0-004f-11e8-91f9-2bf51ba4c0f1.png">

What it should look like:

<img width="251" alt="2018-01-23 03 08 28 pm" src="https://user-images.githubusercontent.com/18408413/35298188-5689bc48-004f-11e8-8029-82b0a283fb7b.png">

**Comment by vleong2332** [comment]
@RassanGrant, without looking at the code, I estimate 10-30 minutes of work for this. I can work on it tonight. Is that okay?

**Comment by RassanGrant** [comment]
Yep works, go ahead
