### ISSUE TITLE
TopBar Update

### ISSUE THREAD

**Issue by RassanGrant** [Norstone/norstone.github.io#233]
Hi @vleong2332 - 

I have a new item I'd like to investigate with you. I have designed a light grey "Top Bar" banner that I am interested in having implemented a certain way. Here is the basic gist of the design:
![top-bar-design](https://user-images.githubusercontent.com/18408413/35443189-34b57a6e-0278-11e8-8b5c-da25cc601eab.jpg)

Very basic in design, but what I am looking for is in the animation of the text inside the top bar. Here is a basic example of what I would like: https://tilebar.com/. You will notice they too have a top bar, except it rotates down different text slogans such as "Fast Free Shipping" and "365 Day Returns" - I do not want our text to constantly rotate, but I DO want it to float down in an identical manner whenever the page loads. That way it catches your eye, but it's not a distraction. Is this something you can do?

**Comment by vleong2332** [comment]
@RassanGrant I sure can. Could you answer a few questions to help me understand the scope?

1. Is this something you want to do for all the pages?
2. What about for medium and small screens?
3. If I understand you correctly, there's only going to be one set of text that floats down whenever a page is initially loaded. Are those texts going to be what you showed in the above mockup?
4. Is that text going to be the same for medium and small screens?
5. Do you want a delay between when the page loads and the top bar showing the text?

**Comment by RassanGrant** [comment]
Hey @vleong2332 - You got it, here are the answers to your questions:
1. All Pages
2. Medium yes, small screens no
3. Yep, let's go with the text I provided.
4. Text will be the same for medium.
5. Yep,  I would like the "Bar" section to be pre-loaded with the webpage's regular css, and then a very brief delay where the text catches your eye/floats down from the top. If we can make it identical to Tilebar's animation timing and all would be perfect.

Thanks, Vicky!

**Comment by vleong2332** [comment]
Thanks for the clarification, Rassan.

Since we're having two text (one to the left and the other to the right), how do you want to handle collision? Collision can happen when the text are too long or if there's no enough space between them.

My idea would be to put a hard limit on the elements that contain the text (for example, 60-40 split). If the text is longer, show an ellipsis (`...`) at the end. This will keep the top bar in one line and force the editor to be mindful what is being put on the top bar. What do you think?

**Comment by RassanGrant** [comment]
Yep, that sounds like a great solution with th elipses

**Comment by vleong2332** [comment]
Where do you want the "REQUEST A SAMPLE" to go?

**Comment by RassanGrant** [comment]
Right side

**Comment by vleong2332** [comment]
Sorry, I wasn't being clear. Where do you want the "REQUEST A SAMPLE" text to link to?

**Comment by RassanGrant** [comment]
Hey @vleong2332 - I updated the Request a sample link, reduced the font size, and padding above and below. 

I realize now, looking at it in action, that it's distracting for the floating - Is there a way to have that do it just once when the visitor lands on the site and then have it be static thereafter? If not, then let's just turn it off for the time being.

**Comment by vleong2332** [comment]
@RassanGrant, could you clarify the "once" part? Are you talking about just the very first time someone visits the website and then never floats it again? or just do it once for every browser session?

**Comment by RassanGrant** [comment]
Hey @vleong2332 - I would say that both of those are suitable. The key is that it doesnt animate (float) whenever a user moves between pages. i think it's a nice effect on entrance, but once i get down to the business of navigating the site I would rather it remain static. Does that make sense?

**Comment by vleong2332** [comment]
@RassanGrant Okay. I'll start on floating it once per page session. Since this is a spec change, I will have to change how it currently works. Because of that I estimate 30 minutes to 1 hour. I can do it within 24 hour of confirmation. Is that okay?

**Comment by RassanGrant** [comment]
Confirmed, thanks!
