### ISSUE TITLE
Add Ratings Schema to White Quartz Rock Panel Page

### ISSUE THREAD

**Issue by RassanGrant** [Norstone/norstone.github.io#239]
Hi @vleong2332 - 

Could you please add this schema to our White Quartz Rock Panel Page: 

https://www.norstoneusa.com/products/rock-panels/white/

<script type="application/ld+json">
{
  "@context": "http://schema.org/",
  "@type": "Product",
  "name": "White Stacked Stone RockPANELS™",
  "description": "Stacked White Quartz Panels for Walls.",
  "aggregateRating": {
    "@type": "AggregateRating",
     "ratingValue": "4.8",
     "reviewCount": "273"
  }
}
</script>

**Comment by vleong2332** [comment]
@RassanGrant What is that for?

**Comment by RassanGrant** [comment]
Hey Vicky - This is schema.org markup - It's how websites are able to obtain "star ratings" in Google Search results. We're looking to test this out on the White Quartz product page to start with. 

I would do this one myself but my Ruby is still messed up.

**Comment by vleong2332** [comment]
From what I see in `#static-conversion`, you got this resolved?

**Comment by RassanGrant** [comment]
Yep resolved, thank you!
