### ISSUE TITLE
Topbar - Mobile

### ISSUE THREAD

**Issue by RassanGrant** [Norstone/norstone.github.io#243]
Hey @vleong2332 - After reviewing the TopBar when it was available on mobile, I took a liking to it. The only thing I'd like to change for mobile is to have separate (shorter) text for the mobile viewset. Can you organize?

<img width="370" alt="2018-02-06 04 57 59 pm" src="https://user-images.githubusercontent.com/18408413/35886452-16e2a9fe-0b5f-11e8-8e48-65d52f3d41be.png">

**Comment by vleong2332** [comment]
@RassanGrant what text do you want for mobile?

**Comment by RassanGrant** [comment]
For now, let's use this as a placeholder:

"Questions? Call (877) 210-9248 for assistance with your project"

**Comment by vleong2332** [comment]
@RassanGrant Should take only 10 minutes max and I can do it now.

**Comment by RassanGrant** [comment]
HI @vleong2332 - Looks good here - Question - Can you provide an x on the top bar so that folks can close it out if they like?

**Comment by vleong2332** [comment]
@RassanGrant Sorry. I thought I had reply to this via email. Since this one is merged, could you close this issue and make a different one for the close button?
