### ISSUE TITLE
Browser Cross-Testing - Issue with "Trademark" Symbol

### ISSUE THREAD

**Issue by RassanGrant** [Norstone/norstone.github.io#250]
Hey @vleong2332 - 

We're having some issues with the trademark symbol showing up with an odd stroke effect on Edge Browsers on this page: https://www.norstoneusa.com/products/large-format-stone-veneer/

We are also seeing an over-sized version of the TM on IE 9, 10, and 11 - We were wondering if you could find a way to make the Trademark symbol look less bold and more properly sized for both Edge and Internet Explorer. 

![2018-02-22 06 06 59 pm](https://user-images.githubusercontent.com/18408413/36569765-12fa8726-17fd-11e8-83bb-2544cbf7b0ba.png)

If you have any questions, just let me know. Thanks, Vicky!

**Comment by vleong2332** [comment]
@RassanGrant I'll look into this on my Edge and IE 11. I don't know if I can still download IE 9 and 10, but I'll see what I can do.

**Comment by vleong2332** [comment]
@RassanGrant We talked about using an icon for this. I'm thinking of including this font-awesome icon set that has the [trademark icon](https://fontawesome.com/icons?d=gallery&q=trademark&m=free).

Pros:
- Free
- Easy to install
- Style-able
- Brings a lot of icon to our arsenal
- Served by a CDN

Cons:
- Slightly more bytes to transfer over the wire
- In the unlikely event that their CDN fails we'll lose integration (there's a backup strategy for this)
- Working offline needs the backup strategy

I'm estimating 10-20 minutes to implement it the recommended way. The backup strategy adds another 10-20 minutes.

Let me know what you think.

**Comment by RassanGrant** [comment]
Hey @vleong2332 - We are a go on this, let's move forward with it.

**Comment by vleong2332** [comment]
Okay. I'll do this tonight.

**Comment by vleong2332** [comment]
@RassanGrant I did the icon for Planc product page and pushed it to `trademark-icons` branch. Do you want to check it out and see if it's okay? Besides the Planc page, where else do you want that trademark icon?
