### ISSUE TITLE
Dynamic Text Insertion by Time of Day / Day of Week

### ISSUE THREAD

**Issue by RassanGrant** [Norstone/norstone.github.io#257]
Hey @vleong2332 - Curious if you would be able to tell me if it's possible to insert a piece of text on our contact page (ie, We're Currently Open) and have it only show up from 9-5 EST, and M-F? 

Here are examples of what I'm looking for:
![call-cta](https://user-images.githubusercontent.com/18408413/36941005-2ea179ca-1f1f-11e8-9a37-6356ccfa8543.jpg)

For Mobile:
![2018-03-03 07 56 39 pm](https://user-images.githubusercontent.com/18408413/36941007-386ec282-1f1f-11e8-81c0-8b33e2011128.jpg)

**Comment by vleong2332** [comment]
@RassanGrant It's certainly possible. Let me think about it a bit more for an estimate.

**Comment by vleong2332** [comment]
@RassanGrant I estimate 1.25-2 hours for inserting the text and the script that determines whether it should show or not.

**Comment by RassanGrant** [comment]
Sounds good, let’s get this in motion

**Comment by vleong2332** [comment]
@RassanGrant I submitted a PR but forgot to notify you. It's PR #261.
