### ISSUE TITLE
Styling of new Check box and Radial Verbiage on Contact Form

### ISSUE THREAD

**Issue by RassanGrant** [Norstone/norstone.github.io#265]
Hey @vleong2332 - I opened up the [contact page](https://www.norstoneusa.com/contact-us/) on Safari for Mac (Desktop) and noticed that the product categories and feet2 and meters2 font is black: 

<img width="490" alt="2018-03-12 05 43 07 pm" src="https://user-images.githubusercontent.com/18408413/37311281-118e3ea4-261d-11e8-90ed-72e150b1aa7b.png">

Can you make sure this is styled like this across the main browsers and devices:

<img width="487" alt="2018-03-12 05 45 21 pm" src="https://user-images.githubusercontent.com/18408413/37311308-2642f772-261d-11e8-9a89-5a0142496092.png">

**Comment by vleong2332** [comment]
@RassanGrant Is it still black if you open it now? I just tried it on Safari on Mac (Desktop) and it looked fine.

![image](https://user-images.githubusercontent.com/11132446/37690445-5b721922-2c81-11e8-94d7-2a98ba09f377.png)

**Comment by RassanGrant** [comment]
Looks good, thanks Vicky!
