### ISSUE TITLE
Houzz/Pinterest/Facebook/Twitter Links

### ISSUE THREAD

**Issue by RassanGrant** [Norstone/norstone.github.io#267]
Hey @vleong2332 - Can you please adjust the outbound links in the social bar on the top right of our website open in a new browser tab instead of sending people off of our website?

**Comment by vleong2332** [comment]
Sure. Is 10 minutes good?

**Comment by RassanGrant** [comment]
Yep

Best,
Rassan

Director | NorstoneUSA
Ph: 321.438.6420
Em: Rassan@norstoneusa.com<mailto:Rassan@norstoneusa.com>

Sent from my iPhone

On Mar 19, 2018, at 10:09 PM, Vicky Leong <notifications@github.com<mailto:notifications@github.com>> wrote:


Sure. Is 10 minutes good?

**Comment by vleong2332** [comment]
@RassanGrant It's done and available for review on branch `links-new-tab`.
