### ISSUE TITLE
Placement of radials on Home Page Banner

### ISSUE THREAD

**Issue by RassanGrant** [Norstone/norstone.github.io#272]
Hey @vleong2332 - 

Can you adjust the positioning of the radials on the banner on the home page? Right now they are pushed all the way to the right, like below:

<img width="1478" alt="2018-05-08 09 21 02 pm" src="https://user-images.githubusercontent.com/18408413/39790803-ff90f208-5305-11e8-91d0-fe67995f0ccd.png">

Ideally we'd like it to sit just on the inside of the last menu item (Contact Us), like so:

<img width="1111" alt="2018-05-08 09 20 46 pm" src="https://user-images.githubusercontent.com/18408413/39790817-109ee0a0-5306-11e8-8bb7-d07038b7f812.png">

**Comment by RassanGrant** [comment]
Hey @vleong2332 - Did you receive this notification?

**Comment by vleong2332** [comment]
@RassanGrant I did, but I forgot to reply. I apologize.

The end of contact us doesn't align with the right-side end-of-container (the how to buy button and the view install guide). Would you rather the radials line up with the end of contact us or the actual end-of-container?

**Comment by RassanGrant** [comment]
Lets go with whatever is closest to the mock-up image, I think that is the contact us

Best,
Rassan

Director | NorstoneUSA
Ph: 321.438.6420
Em: Rassan@norstoneusa.com<mailto:Rassan@norstoneusa.com>

Sent from my iPhone

On May 10, 2018, at 10:09 PM, Vicky Leong <notifications@github.com<mailto:notifications@github.com>> wrote:


@RassanGrant<https://github.com/RassanGrant> I did, but I forgot to reply. I apologize.

The end of contact us doesn't align with the right-side end-of-container (the how to buy button and the view install guide). Would you rather the radials line up with the end of contact us or the actual end-of-container?

**Comment by vleong2332** [comment]
It's ready for your review.
