### ISSUE TITLE
No-Index for a single link

### ISSUE THREAD

**Issue by RassanGrant** [Norstone/norstone.github.io#285]
Hi @vleong2332  - 

Can you please no-index this particular blog post for us?

https://www.norstoneusa.com/blog/info-to-purchase-norstone/

**Comment by vleong2332** [comment]
@RassanGrant Check out the PR #287 to see how you could add the same no-index rule to other blog posts.

If you want to verify the work, you can pull down the branch, build, go to the page, and inspect the elements for the `<meta name="robots" content="noindex" />`
