### ISSUE TITLE
SalesIQ Tracking Installation

### ISSUE THREAD

**Issue by RassanGrant** [Norstone/norstone.github.io#295]
HI @vleong2332 - 

Can you please install the following code for us? Here are the instructions:

- SalesIQ helps you to track and analyze the visitors visiting your website and reports the info like the location of your visitors and shows you what page they are visiting, web actions performed on the website and much more.
- How to install this code on the website?
 - Copy the Visitor tracking code.In your website's source file, "paste" the code into the existing code anywhere before the </body> tag.
- "Save" and "Publish" the changes made to your website.

**Code**
<script type="text/javascript">
var $zoho=$zoho || {};$zoho.salesiq = $zoho.salesiq || {widgetcode:"587b877c0defdf8e751f0e57b85dfc45ae809f0bd6998ca30934ab343d15a54c", values:{},ready:function(){}};var d=document;s=d.createElement("script");s.type="text/javascript";s.id="zsiqscript";s.defer=true;s.src="https://salesiq.zoho.com/widget";t=d.getElementsByTagName("script")[0];t.parentNode.insertBefore(s,t);d.write("<div id='zsiqwidget'></div>");
</script>

**Comment by vleong2332** [comment]
Hi, @RassanGrant. Sure.

When it says

> Copy the Visitor tracking code.In your website's source file, "paste" the code into the existing code anywhere before the tag.

Do you know what tag it's referring to?

**Comment by RassanGrant** [comment]
Yep: 

In your website's source file, "paste" the code into the existing code anywhere before the </body> tag

**Comment by RassanGrant** [comment]
oh weird - github must be reading the code since these are html comments - it's before the body tag

**Comment by vleong2332** [comment]
Hah. That's amusing. I'll do it tonight. It shouldn't take long at all, but how can I verify that it works on Zoho's end?

**Comment by RassanGrant** [comment]
I'll have to do that @vleong2332 - I'd say let's go ahead and get it implemented and, as long as it's not messing up the site in any way, I can track it via their reporting terminal.
