### ISSUE TITLE
Google Tag installation

### ISSUE THREAD

**Issue by RassanGrant** [Norstone/norstone.github.io#311]
@vleong2332 - 

Can you please help us install Google Tag Manager?

Here are the instructions:
Copy the code below and paste it onto every page of your website.
Paste this code as high in the <head> of the page as possible:

<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-NW6749T');</script>

Additionally, paste this code immediately after the opening <body> tag:

<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-NW6749T"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>

For more information about installing the Google Tag Manager snippet, visit our Quick Start Guide: https://developers.google.com/tag-manager/quickstart

**Comment by vleong2332** [comment]
Sure. Let me read up on the developer guide and give you an estimate.

**Comment by vleong2332** [comment]
Looks pretty straightforward. Should take me 20-30 mins to:
- install the code,
- deploy,
- and verify that it talks to GTM (This will be a one-sided check for me. You may need to also verify on the other end).

**Comment by RassanGrant** [comment]
Hey @vleong2332 - Perfect, any chance you could get around to this today?

**Comment by vleong2332** [comment]
I can squeeze this in at lunch (noon).

**Comment by RassanGrant** [comment]
Perfect, can you just ping me over on Slack when you are starting work on it? I'd like to follow along. Thank you!
