### ISSUE TITLE
Fix new branch "fix-Ip-update"

### ISSUE THREAD

**Issue by RassanGrant** [Norstone/norstone.github.io#319]
Hi @vleong2332 - 

I tried updating our IP Address javascript on the organic site today from old code leftover from Albert, and I cant seem to get the site to build. It keeps failing at "compile static assets."

Can you look into it and get it fixed for me? Once it's passed, we'll want to confirm that the forms are capturing the IP address again. Thanks!

**Comment by vleong2332** [comment]
@RassanGrant I fixed the errors that caused the build to fail. I also adjusted the URL that it talks to to get the data.

Unfortunately, the network call that it makes failed to retrieve the user's IP address when it's done locally on my machine. The error that it returns suggests that I won't be able to do it locally. I'm going to have to deploy it to check.

**Comment by vleong2332** [comment]
Here it is in production. That loaded my IP address into the hidden input field.

![image](https://user-images.githubusercontent.com/11132446/54578612-be892a00-49d6-11e9-926b-f2eb5e744d96.png)
